const vscode = require('vscode');

function activate(context) {
  let badgeEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.badges');
  let badge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.badge');
  let colorEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.color');
  let activeFileEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.activeFile');
  let activeBadge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.activeBadge');
  let propagateEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.propagate');

  // Generated by Copilot: create provider when either color or badges (or both) are enabled
  let decClass = colorEnabled || badgeEnabled ? new OpenFileDecorationProvider(badgeEnabled, badge, activeFileEnabled, activeBadge, propagateEnabled) : null;

  context.subscriptions.push(
    { dispose: () => decClass?.dispose() },
    vscode.workspace.onDidChangeConfiguration((event) => {
      if (!event.affectsConfiguration('highlightOpenFiles')) return;

      colorEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.color');
      badgeEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.badges');
      badge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.badge');
      activeFileEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.activeFile');
      activeBadge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.activeBadge');
      propagateEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.propagate');

      decClass?.dispose();
      decClass = colorEnabled || badgeEnabled ? new OpenFileDecorationProvider(badgeEnabled, badge, activeFileEnabled, activeBadge, propagateEnabled) : null;
    }),
  );
}

class OpenFileDecorationProvider {
  constructor(badgeEnabled, badge, activeFileEnabled, activeBadge, propagateEnabled) {
    this._badgeEnabled = badgeEnabled;
    this._badge = badge;
    this._activeFileEnabled = activeFileEnabled;
    this._activeBadge = activeBadge;
    this._propagateEnabled = propagateEnabled;
    this._emitter = new vscode.EventEmitter();
    this.onDidChangeFileDecorations = this._emitter.event;
    this._openPathsCache = null;
    this._activeUri = vscode.window.activeTextEditor?.document.uri;

    this._disposables = [
      vscode.window.registerFileDecorationProvider(this),
      // Generated by Copilot
      vscode.window.tabGroups.onDidChangeTabs((event) => {
        this._openPathsCache = null;
        const changedUris = [...event.opened, ...event.closed, ...event.changed].map((tab) => tab.input?.uri).filter(Boolean);
        // Fire only the affected URIs to avoid refreshing (and flickering) all badges
        this._emitter.fire(changedUris.length > 0 ? changedUris : undefined);
      }),
      vscode.window.onDidChangeActiveTextEditor((editor) => {
        const prev = this._activeUri;
        this._activeUri = editor?.document.uri;
        // Fire only the previously active and newly active URIs to avoid flickering
        this._emitter.fire([prev, this._activeUri].filter(Boolean));
      }),
    ];
  }

  _getOpenPaths() {
    if (!this._openPathsCache) {
      this._openPathsCache = new Set(
        vscode.window.tabGroups.all
          .flatMap((g) => g.tabs)
          .map((t) => t.input?.uri?.fsPath)
          .filter(Boolean),
      );
    }
    return this._openPathsCache;
  }

  provideFileDecoration(uri) {
    if (uri.scheme !== 'file') return;

    const openPaths = this._getOpenPaths();
    if (!openPaths.has(uri.fsPath)) return;

    const isActive = this._activeFileEnabled && this._activeUri?.fsPath === uri.fsPath;

    return {
      color: new vscode.ThemeColor(isActive ? 'highlightOpenFiles.activeFile' : 'highlightOpenFiles.openFiles'),
      badge: this._badgeEnabled ? (isActive ? this._activeBadge : this._badge) : undefined,
      tooltip: isActive ? 'Active file' : 'File is open in editor',
      propagate: this._propagateEnabled,
    };
  }

  dispose() {
    this._disposables.forEach((d) => d.dispose());
    this._emitter.dispose();
  }
}

function deactivate() {}

module.exports = { activate, deactivate };
