// Generated by Copilot
const vscode = require('vscode');

function activate(context) {
  let badgeEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.badges');
  let badge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.badge');
  let colorEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.color');

  let decClass = colorEnabled ? new OpenFileDecorationProvider(badgeEnabled, badge) : null;

  context.subscriptions.push(
    { dispose: () => decClass?.dispose() },
    vscode.workspace.onDidChangeConfiguration((event) => {
      if (event.affectsConfiguration('highlightOpenFiles.decorations.enable.color')) {
        colorEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.color');
        if (colorEnabled) {
          decClass = new OpenFileDecorationProvider(badgeEnabled, badge);
        } else {
          decClass?.dispose();
          decClass = null;
        }
      } else if (event.affectsConfiguration('highlightOpenFiles.decorations.enable.badges')) {
        badgeEnabled = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.enable.badges');
        if (colorEnabled) {
          decClass?.dispose();
          decClass = new OpenFileDecorationProvider(badgeEnabled, badge);
        }
      } else if (event.affectsConfiguration('highlightOpenFiles.decorations.badge')) {
        badge = vscode.workspace.getConfiguration().get('highlightOpenFiles.decorations.badge');
        if (colorEnabled) {
          decClass?.dispose();
          decClass = new OpenFileDecorationProvider(badgeEnabled, badge);
        }
      }
    }),
  );
}

class OpenFileDecorationProvider {
  constructor(badgeEnabled, badge) {
    this._badgeEnabled = badgeEnabled;
    this._badge = badge;
    this._emitter = new vscode.EventEmitter();
    this.onDidChangeFileDecorations = this._emitter.event;

    this._disposables = [
      vscode.window.registerFileDecorationProvider(this),
      vscode.window.tabGroups.onDidChangeTabs(() => {
        this._emitter.fire(undefined); // undefined = refresh all
      }),
    ];
  }

  _getOpenPaths() {
    return new Set(
      vscode.window.tabGroups.all
        .flatMap((g) => g.tabs)
        .map((t) => t.input?.uri?.fsPath)
        .filter(Boolean),
    );
  }

  provideFileDecoration(uri) {
    if (uri.scheme !== 'file') return;

    const openPaths = this._getOpenPaths();
    if (!openPaths.has(uri.fsPath)) return;

    return {
      color: new vscode.ThemeColor('highlightOpenFiles.openFiles'),
      badge: this._badgeEnabled ? this._badge : undefined,
      tooltip: 'File is open in editor',
    };
  }

  dispose() {
    this._disposables.forEach((d) => d.dispose());
    this._emitter.dispose();
  }
}

function deactivate() {}

module.exports = { activate, deactivate };
